"""
Setup Helper — Opens free API signup pages and saves keys to .env automatically.
Run this ONCE to get all your free API keys.

Usage: python setup_keys.py
"""

import webbrowser
import time
import sys
import os
from pathlib import Path

ENV_FILE = Path(__file__).parent / ".env"
ENV_TEMPLATE = Path(__file__).parent / ".env.template"


def load_env():
    """Load existing .env values."""
    values = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, val = line.split("=", 1)
                values[key.strip()] = val.strip()
    return values


def save_env(values: dict):
    """Save values to .env file."""
    lines = [
        "# ============================================================",
        "# FREE API KEYS - Auto-generated by setup_keys.py",
        "# ============================================================",
        "",
        "# Google Gemini API (Free: 15 requests/min, 1M tokens/day)",
        f"GEMINI_API_KEY={values.get('GEMINI_API_KEY', '')}",
        "",
        "# YouTube Data API v3 (Free: 10,000 quota units/day)",
        f"YOUTUBE_CLIENT_ID={values.get('YOUTUBE_CLIENT_ID', '')}",
        f"YOUTUBE_CLIENT_SECRET={values.get('YOUTUBE_CLIENT_SECRET', '')}",
        "",
        "# Telegram Bot (Free: Unlimited messages)",
        f"TELEGRAM_BOT_TOKEN={values.get('TELEGRAM_BOT_TOKEN', '')}",
        f"TELEGRAM_CHAT_ID={values.get('TELEGRAM_CHAT_ID', '')}",
        "",
    ]
    ENV_FILE.write_text("\n".join(lines), encoding="utf-8")


def is_set(val):
    """Check if a value is actually set (not placeholder)."""
    placeholders = ["", "your_gemini_api_key_here", "your_youtube_client_id_here",
                     "your_youtube_client_secret_here", "your_telegram_bot_token_here",
                     "your_telegram_chat_id_here"]
    return val and val not in placeholders


def main():
    sys.stdout.reconfigure(encoding="utf-8")

    print("\n" + "=" * 60)
    print("  FREE API KEY SETUP - All keys are 100% FREE")
    print("=" * 60)
    print("\nThis tool will:")
    print("  1. Open browser tabs for each free signup")
    print("  2. Let you paste your keys right here")
    print("  3. Save them to .env automatically\n")

    # Load existing values
    env = load_env()

    # ── Step 1: Gemini API Key ──────────────────────────────
    print("-" * 50)
    print("  STEP 1/3: Google Gemini API Key")
    print("  Cost: FREE (15 requests/min, 1M tokens/day)")
    print("-" * 50)
    
    current = env.get("GEMINI_API_KEY", "")
    if is_set(current):
        print(f"  Already set: {current[:8]}...{current[-4:]}")
        change = input("  Keep existing? (Y/n): ").strip().lower()
        if change != "n":
            print("  Keeping existing key.")
        else:
            current = ""
    
    if not is_set(current):
        print("\n  Instructions:")
        print("    1. Sign in with your Google account")
        print("    2. Click 'Create API Key'")
        print("    3. Select any project (or create new)")
        print("    4. Copy the key\n")
        
        input("  Press ENTER to open Google AI Studio...")
        webbrowser.open("https://aistudio.google.com/apikey")
        print("  Browser opened!")
        
        while True:
            key = input("\n  Paste your Gemini API Key here: ").strip()
            if key and len(key) > 10:
                env["GEMINI_API_KEY"] = key
                print(f"  Saved: {key[:8]}...{key[-4:]}")
                break
            else:
                print("  Invalid key. Try again (or type 'skip' to skip)")
                if key.lower() == "skip":
                    break

    # ── Step 2: YouTube Data API v3 ─────────────────────────
    print("\n" + "-" * 50)
    print("  STEP 2/3: YouTube Data API v3 (OAuth2)")
    print("  Cost: FREE (10,000 quota units/day = ~6 uploads)")
    print("-" * 50)
    
    current_id = env.get("YOUTUBE_CLIENT_ID", "")
    if is_set(current_id):
        print(f"  Already set: {current_id[:15]}...")
        change = input("  Keep existing? (Y/n): ").strip().lower()
        if change != "n":
            print("  Keeping existing credentials.")
            current_id = "KEEP"
    
    if current_id != "KEEP" and not is_set(current_id):
        print("\n  Instructions:")
        print("    1. Create a new project (or use existing)")
        print("    2. Click 'Enable' on YouTube Data API v3")
        print("    3. Go to 'APIs & Services' > 'Credentials'")
        print("    4. Click '+ CREATE CREDENTIALS' > 'OAuth 2.0 Client ID'")
        print("    5. Application type: 'Desktop app'")
        print("    6. Copy Client ID and Client Secret")
        print("    7. Go to 'OAuth consent screen' > add your email as test user\n")
        
        input("  Press ENTER to open Google Cloud Console...")
        webbrowser.open("https://console.cloud.google.com/apis/library/youtube.googleapis.com")
        print("  Browser opened!")
        
        while True:
            client_id = input("\n  Paste YouTube Client ID: ").strip()
            if client_id and len(client_id) > 10:
                env["YOUTUBE_CLIENT_ID"] = client_id
                break
            elif client_id.lower() == "skip":
                break
            else:
                print("  Invalid. Try again or type 'skip'.")
        
        if client_id.lower() != "skip":
            while True:
                secret = input("  Paste YouTube Client Secret: ").strip()
                if secret and len(secret) > 5:
                    env["YOUTUBE_CLIENT_SECRET"] = secret
                    print("  YouTube credentials saved!")
                    break
                elif secret.lower() == "skip":
                    break
                else:
                    print("  Invalid. Try again or type 'skip'.")

    # ── Step 3: Telegram Bot ────────────────────────────────
    print("\n" + "-" * 50)
    print("  STEP 3/3: Telegram Bot")
    print("  Cost: FREE (Unlimited messages)")
    print("-" * 50)
    
    current_token = env.get("TELEGRAM_BOT_TOKEN", "")
    if is_set(current_token):
        print(f"  Already set: {current_token[:10]}...")
        change = input("  Keep existing? (Y/n): ").strip().lower()
        if change != "n":
            print("  Keeping existing token.")
            current_token = "KEEP"
    
    if current_token != "KEEP" and not is_set(current_token):
        print("\n  Instructions:")
        print("    1. Open Telegram app")
        print("    2. Search for @BotFather")
        print("    3. Send /newbot and follow prompts")
        print("    4. Copy the Bot Token")
        print("    5. Then search @userinfobot > send /start > copy your Chat ID")
        print("    6. IMPORTANT: Start a chat with your new bot (send it any message)\n")
        
        input("  Press ENTER to open Telegram BotFather...")
        webbrowser.open("https://t.me/BotFather")
        print("  Browser opened!")
        
        while True:
            token = input("\n  Paste Telegram Bot Token: ").strip()
            if token and ":" in token:
                env["TELEGRAM_BOT_TOKEN"] = token
                break
            elif token.lower() == "skip":
                break
            else:
                print("  Invalid token (should contain ':'). Try again or type 'skip'.")
        
        if token.lower() != "skip":
            print("\n  Now get your Chat ID:")
            print("  Search @userinfobot in Telegram > send /start\n")
            
            input("  Press ENTER to open userinfobot...")
            webbrowser.open("https://t.me/userinfobot")
            
            while True:
                chat_id = input("\n  Paste your Telegram Chat ID: ").strip()
                if chat_id and chat_id.lstrip("-").isdigit():
                    env["TELEGRAM_CHAT_ID"] = chat_id
                    print("  Telegram credentials saved!")
                    break
                elif chat_id.lower() == "skip":
                    break
                else:
                    print("  Invalid Chat ID (should be a number). Try again or type 'skip'.")

    # ── Save everything ─────────────────────────────────────
    save_env(env)
    print("\n" + "=" * 60)
    print("  SETUP COMPLETE!")
    print("=" * 60)

    # Show summary
    print("\n  Key Status:")
    checks = [
        ("Gemini API", "GEMINI_API_KEY"),
        ("YouTube Client ID", "YOUTUBE_CLIENT_ID"),
        ("YouTube Client Secret", "YOUTUBE_CLIENT_SECRET"),
        ("Telegram Bot Token", "TELEGRAM_BOT_TOKEN"),
        ("Telegram Chat ID", "TELEGRAM_CHAT_ID"),
    ]
    all_set = True
    for label, key in checks:
        val = env.get(key, "")
        status = "[OK]" if is_set(val) else "[MISSING]"
        if not is_set(val):
            all_set = False
        print(f"    {status} {label}")

    print(f"\n  .env saved to: {ENV_FILE}")

    if all_set:
        print("\n  All keys configured! Next steps:")
        print("    python main.py --dry-run    # Test locally (no upload)")
        print("    python main.py              # Full pipeline with upload")
    else:
        print("\n  Some keys are missing. Re-run this script to add them:")
        print("    python setup_keys.py")

    print()


if __name__ == "__main__":
    main()
